#!/bin/bash

echo "`date -uIns` - gunicorn/run $@"

# Poll Triton status endpoint
while true; do
    status=$(curl -w "%{http_code}\n" http://localhost:8000/v2/health/ready | tail -1)
    if [ $status -eq 200 ]; then
        echo "`date -uIns` - Triton server ready, starting workers ..."
        break
    fi
    echo "`date -uIns` - Waiting for Triton server to get ready ..."
    sleep 5
done

if [[ -z "${AZUREML_CONDA_ENVIRONMENT_PATH}" ]]; then
    export LD_LIBRARY_PATH="$(conda info --root)/lib:$LD_LIBRARY_PATH"
else
    export LD_LIBRARY_PATH="$AZUREML_CONDA_ENVIRONMENT_PATH/lib:$LD_LIBRARY_PATH"
fi

export PYTHONPATH="${AML_SERVER_ROOT:-/var/azureml-server}:$PYTHONPATH"

cd "${AML_APP_ROOT:-/var/azureml-app}"
exec gunicorn -c "${AML_SERVER_ROOT:-/var/azureml-server}/gunicorn_conf.py" "wsgi:app"
